import type {
  Beam,
  CommonResponse,
  CurrencyContentResponse,
  InventoryQueryRequest,
  InventoryUpdateRequest,
  InventoryView,
  ItemContentResponse,
  MultipliersGetResponse,
  TransferRequest,
  EndTransactionRequest,
} from "beamable-sdk"
import {
  inventoryDeleteTransactionByObjectId,
  inventoryGetByObjectId,
  inventoryGetCurrencyBasic,
  inventoryGetItemsBasic,
  inventoryGetMultipliersByObjectId,
  inventoryPostByObjectId,
  inventoryPutByObjectId,
  inventoryPutPreviewByObjectId,
  inventoryPutProxyReloadByObjectId,
  inventoryPutTransferByObjectId,
} from "beamable-sdk/api"

/**
 * Inventory helpers using the autogenerated OpenAPI functions (per API reference HTML in docs).
 */
type InventoryScope = {
  objectId?: bigint | string
  scope?: string
  gamertag?: string
}

const currentPlayerId = (beam: Beam, objectId?: bigint | string) => objectId ?? beam.player.id

const unwrap = async <T>(resPromise: Promise<{ data: T }>) => (await resPromise).data

export const fetchInventory = (
  beam: Beam,
  options: InventoryScope = {},
): Promise<InventoryView> => {
  console.log("[BeamInventory] Fetching inventory", options)
  const { objectId, scope, gamertag } = options
  return unwrap(
    inventoryGetByObjectId(
      beam.requester,
      currentPlayerId(beam, objectId),
      scope,
      gamertag,
    ),
  )
}

export const fetchItems = (beam: Beam, gamertag?: string): Promise<ItemContentResponse> => {
  console.log("[BeamInventory] Fetching items", { gamertag })
  return unwrap(inventoryGetItemsBasic(beam.requester, gamertag))
}

export const fetchCurrencies = (beam: Beam, gamertag?: string): Promise<CurrencyContentResponse> => {
  console.log("[BeamInventory] Fetching currencies", { gamertag })
  return unwrap(inventoryGetCurrencyBasic(beam.requester, gamertag))
}

export const fetchMultipliers = (
  beam: Beam,
  objectId?: bigint | string,
  gamertag?: string,
): Promise<MultipliersGetResponse> => {
  console.log("[BeamInventory] Fetching multipliers", { objectId, gamertag })
  return unwrap(
    inventoryGetMultipliersByObjectId(
      beam.requester,
      currentPlayerId(beam, objectId),
      gamertag,
    ),
  )
}

export const queryInventory = (
  beam: Beam,
  payload: InventoryQueryRequest,
  options: Pick<InventoryScope, "objectId" | "gamertag"> = {},
): Promise<InventoryView> => {
  console.log("[BeamInventory] Query inventory", { payload, options })
  return unwrap(
    inventoryPostByObjectId(
      beam.requester,
      currentPlayerId(beam, options.objectId),
      payload,
      options.gamertag,
    ),
  )
}

export const previewUpdate = (
  beam: Beam,
  payload: InventoryUpdateRequest,
  options: Pick<InventoryScope, "objectId" | "gamertag"> = {},
): Promise<CommonResponse> => {
  console.log("[BeamInventory] Preview update", { options })
  return unwrap(
    inventoryPutPreviewByObjectId(
      beam.requester,
      currentPlayerId(beam, options.objectId),
      payload,
      options.gamertag,
    ),
  )
}

export const applyUpdate = (
  beam: Beam,
  payload: InventoryUpdateRequest,
  options: Pick<InventoryScope, "objectId" | "gamertag"> = {},
): Promise<CommonResponse> => {
  console.log("[BeamInventory] Apply update", { options })
  return unwrap(
    inventoryPutByObjectId(
      beam.requester,
      currentPlayerId(beam, options.objectId),
      payload,
      options.gamertag,
    ),
  )
}

export const transferInventory = (
  beam: Beam,
  payload: TransferRequest,
  options: Pick<InventoryScope, "objectId" | "gamertag"> = {},
): Promise<CommonResponse> => {
  console.log("[BeamInventory] Transfer inventory", { options })
  return unwrap(
    inventoryPutTransferByObjectId(
      beam.requester,
      currentPlayerId(beam, options.objectId),
      payload,
      options.gamertag,
    ),
  )
}

export const reloadProxy = (
  beam: Beam,
  options: Pick<InventoryScope, "objectId" | "gamertag"> = {},
): Promise<CommonResponse> => {
  console.log("[BeamInventory] Reload proxy", { options })
  return unwrap(
    inventoryPutProxyReloadByObjectId(
      beam.requester,
      currentPlayerId(beam, options.objectId),
      options.gamertag,
    ),
  )
}

export const endTransaction = (
  beam: Beam,
  payload: EndTransactionRequest,
  options: Pick<InventoryScope, "objectId" | "gamertag"> = {},
): Promise<CommonResponse> => {
  console.log("[BeamInventory] End transaction", { options })
  return unwrap(
    inventoryDeleteTransactionByObjectId(
      beam.requester,
      currentPlayerId(beam, options.objectId),
      payload,
      options.gamertag,
    ),
  )
}
