using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Api.Autogenerated.Realms;
using Beamable.Common;
using Beamable.Server;
using Beamable.Server.Api.RealmConfig;
using Beamable.StellarFederation.Features.Common;

namespace Beamable.StellarFederation;

public class Configuration : IService
{
    private const string ConfigurationNamespace = "stellar-federation";
    private readonly IRealmConfigService _realmConfigService;
    private readonly RealmsApi _realmsApi;

    public readonly string RealmSecret = Environment.GetEnvironmentVariable("SECRET") ?? "";
    private RealmConfig? _realmConfig;

    public Configuration(IRealmConfigService realmConfigService, SocketRequesterContext socketRequesterContext, RealmsApi realmsApi)
    {
        _realmConfigService = realmConfigService;
        _realmsApi = realmsApi;
        socketRequesterContext.Subscribe<object>(Constants.Features.Services.REALM_CONFIG_UPDATE_EVENT, _ =>
        {
            BeamableLogger.Log("Realm config was updated");
            _realmConfig = null;
        });
    }

    /// <summary>
    /// CONFIG VALUES
    /// To configure an explicit configuration values, visit the Beamable portal and add configuration under Operate -> Config.
    /// Configuration namespace is configured in the <see cref="ConfigurationNamespace"/> constant.
    /// </summary>

    public ValueTask<string> StellarRpc => GetValue(nameof(StellarRpc), "");

    // "public" or "test"
    public ValueTask<string> StellarNetwork => GetValue(nameof(StellarNetwork), StellarSettings.TestNetwork);
    public ValueTask<string> StellarFaucet => GetValue(nameof(StellarFaucet), "https://friendbot.stellar.org/");
    public ValueTask<int> AuthenticationChallengeTtlSec => GetValue(nameof(AuthenticationChallengeTtlSec), 600);
    public ValueTask<string> WalletConnectProjectId => GetValue(nameof(WalletConnectProjectId), "");
    public ValueTask<string> WalletConnectBridgeUrl => GetValue(nameof(WalletConnectBridgeUrl), "");

    private async ValueTask<T> GetValue<T>(string key, T defaultValue) where T : IConvertible
    {
        _realmConfig ??= await _realmConfigService.GetRealmConfigSettings();
        var namespaceConfig = _realmConfig!.GetValueOrDefault(ConfigurationNamespace) ?? new ReadOnlyDictionary<string, string>(new Dictionary<string, string>());
        var value = namespaceConfig.GetValueOrDefault(key);
        if (value is null)
        {
            return defaultValue;
        }
        return (T)Convert.ChangeType(value, typeof(T));
    }

    public async Task Update(string name, string value)
    {
        var currentConfig = await _realmsApi.GetConfig();
        currentConfig.config[$"{ConfigurationNamespace}|{name}"] = value;
        await _realmsApi.PutConfig(new RealmConfigSaveRequest
        {
            config = currentConfig.config
        });
    }
}

internal class ConfigurationException(string message)
    : MicroserviceException((int)HttpStatusCode.BadRequest, "ConfigurationError", message);