//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.StellarFederation.StellarFederation"/> </summary
    public sealed class StellarFederationClient : MicroserviceClient, Beamable.Common.IHaveServiceName, Beamable.Common.ISupportsFederatedInventory<StellarFederationCommon.StellarWeb3Identity>, Beamable.Common.ISupportsFederatedLogin<StellarFederationCommon.StellarWeb3Identity>, Beamable.Common.ISupportsFederatedInventory<StellarFederationCommon.StellarWeb3ExternalIdentity>, Beamable.Common.ISupportsFederatedLogin<StellarFederationCommon.StellarWeb3ExternalIdentity>
    {
        
        public StellarFederationClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public StellarFederationClient(Beamable.Common.Dependencies.IDependencyProvider provider) : 
                base(provider)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "StellarFederation";
            }
        }
        
        /// <summary>
        /// Call the GetRealmAccount method on the StellarFederation microservice
        /// <see cref="Beamable.StellarFederation.StellarFederation.GetRealmAccount"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetRealmAccount()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("StellarFederation", "GetRealmAccount", serializedFields);
        }
        
        /// <summary>
        /// Call the GenerateRealmAccount method on the StellarFederation microservice
        /// <see cref="Beamable.StellarFederation.StellarFederation.GenerateRealmAccount"/>
        /// </summary>
        public Beamable.Common.Promise<string> GenerateRealmAccount()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("StellarFederation", "GenerateRealmAccount", serializedFields);
        }
        
        /// <summary>
        /// Call the StellarConfiguration method on the StellarFederation microservice
        /// <see cref="Beamable.StellarFederation.StellarFederation.StellarConfiguration"/>
        /// </summary>
        public Beamable.Common.Promise<StellarFederationCommon.Models.Response.ConfigurationResponse> StellarConfiguration()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<StellarFederationCommon.Models.Response.ConfigurationResponse>("StellarFederation", "StellarConfiguration", serializedFields);
        }
        
        /// <summary>
        /// Call the UpdateCurrency method on the StellarFederation microservice
        /// <see cref="Beamable.StellarFederation.StellarFederation.UpdateCurrency"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> UpdateCurrency(string currencyContentId, int amount)
        {
            object raw_currencyContentId = currencyContentId;
            object raw_amount = amount;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("currencyContentId", raw_currencyContentId);
            serializedFields.Add("amount", raw_amount);
            return this.Request<Beamable.Common.Unit>("StellarFederation", "UpdateCurrency", serializedFields);
        }
        
        /// <summary>
        /// Call the AddItem method on the StellarFederation microservice
        /// <see cref="Beamable.StellarFederation.StellarFederation.AddItem"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> AddItem(string itemContentId, System.Collections.Generic.Dictionary<System.String, System.String> properties)
        {
            object raw_itemContentId = itemContentId;
            object raw_properties = properties;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("itemContentId", raw_itemContentId);
            serializedFields.Add("properties", raw_properties);
            return this.Request<Beamable.Common.Unit>("StellarFederation", "AddItem", serializedFields);
        }
        
        /// <summary>
        /// Call the RemoveItem method on the StellarFederation microservice
        /// <see cref="Beamable.StellarFederation.StellarFederation.RemoveItem"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> RemoveItem(string itemContentId, long instanceId)
        {
            object raw_itemContentId = itemContentId;
            object raw_instanceId = instanceId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("itemContentId", raw_itemContentId);
            serializedFields.Add("instanceId", raw_instanceId);
            return this.Request<Beamable.Common.Unit>("StellarFederation", "RemoveItem", serializedFields);
        }
        
        /// <summary>
        /// Call the ExternalAddress method on the StellarFederation microservice
        /// <see cref="Beamable.StellarFederation.StellarFederation.ExternalAddress"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ExternalAddress()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<Beamable.Common.Unit>("StellarFederation", "ExternalAddress", serializedFields);
        }
        
        /// <summary>
        /// Call the ExternalSignature method on the StellarFederation microservice
        /// <see cref="Beamable.StellarFederation.StellarFederation.ExternalSignature"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ExternalSignature()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<Beamable.Common.Unit>("StellarFederation", "ExternalSignature", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersStellarFederationClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Collections_Generic_Dictionary_System_String_System_String : MicroserviceClientDataWrapper<System.Collections.Generic.Dictionary<System.String, System.String>>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int64 : MicroserviceClientDataWrapper<long>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForStellarFederationClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute(50, Beamable.Common.Dependencies.RegistrationOrigin.EDITOR | Beamable.Common.Dependencies.RegistrationOrigin.RUNTIME)]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            System.Func<Beamable.Common.Dependencies.IDependencyProvider, StellarFederationClient> factory = p => new StellarFederationClient(p);
            builder.AddScoped<StellarFederationClient>(factory);
        }
        
        public static StellarFederationClient StellarFederation(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<StellarFederationClient>();
        }
    }
}
