using System.Linq;
using Beamable.Api.Autogenerated.Models;
using StellarFederationCommon.Store;

namespace Beamable.StellarFederation.Features.Commerce;

public static class CommerceExtensions
{
public static GetListingsResponse ToGetStoresResponse(this GetActiveOffersResponse response)
    {
        return new GetListingsResponse
        {
            stores = response.stores.Select(s => new StoreView
            {
                title = s.title.HasValue ? s.title.Value : "",
                symbol = s.symbol,
                nextDeltaSeconds = s.nextDeltaSeconds.HasValue ? s.nextDeltaSeconds.Value : 0,
                secondsRemain = s.secondsRemain.HasValue ? s.secondsRemain.Value : 0,
                listings = s.listings.Select(l => new ListingView
                {
                    symbol = l.symbol,
                    active = l.active,
                    secondsActive = l.secondsActive,
                    purchasesRemain = l.purchasesRemain.HasValue ? l.purchasesRemain.Value : 0,
                    secondsRemain = l.secondsRemain.HasValue ? l.secondsRemain.Value : 0,
                    cooldown = l.cooldown.HasValue ? l.cooldown.Value : 0,
                    clientData = l.clientDataList.Select(cd => new ClientDataView
                    {
                        name = cd.name,
                        value = cd.value,
                    }).ToArray(),
                    offer = new OfferView
                    {
                        symbol = l.offer.symbol,
                        titles = l.offer.titles,
                        descriptions = l.offer.descriptions,
                        price = new OfferPriceView
                        {
                            symbol = l.offer.price.symbol,
                            type = l.offer.price.type,
                            amount = l.offer.price.amount,
                            schedule = l.offer.price.schedule.HasValue ? l.offer.price.schedule.Value : System.Array.Empty<int>(),
                        },
                        obtainCurrency = l.offer.obtainCurrency.Select(oc => new ObtainCurrencyView
                        {
                            symbol = oc.symbol,
                            amount = oc.amount
                        }).ToArray(),
                        obtainItems = l.offer.obtainItems.Select(oi => new ObtainItemsView
                        {
                            contentId = oi.contentId,
                            properties = oi.properties.Select(oip => new ItemPropertyView
                            {
                                name = oip.name,
                                value = oip.value,
                            }).ToArray()
                        }).ToArray(),
                    }
                }).ToArray()
            }).ToArray()
        };
    }
}