using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Common.Api;
using Beamable.StellarFederation.Features.Accounts;
using Beamable.StellarFederation.Features.Transactions.Storage;

namespace Beamable.StellarFederation.Features.BlockProcessor;

public class UpdatePlayerStateService : IService
{
    private readonly IBeamableRequester _beamableRequester;

    public UpdatePlayerStateService(IBeamableRequester beamableRequester)
    {
        _beamableRequester = beamableRequester;
    }

    public async Task Update(IEnumerable<long> gamerTags)
    {
        var updates = gamerTags.Select(Update);
        await Task.WhenAll(updates);
    }

    private async Task Update(long gamerTag)
    {
        try
        {
            await SynchronizeState(gamerTag);
        }
        catch (Exception e)
        {
            BeamableLogger.LogException(e);
        }
    }

    private async Task SynchronizeState(long gamerTag)
    {
        try
        {
            BeamableLogger.Log("Reporting back state for user {gamerTag}", gamerTag);
            await _beamableRequester.Request<CommonResponse>(Method.PUT, $"/object/inventory/{gamerTag}/proxy/reload", includeAuthHeader: false);
        }
        catch (Exception e)
        {
            BeamableLogger.LogError("Error synchronizing inventory for user {gamerTag}", gamerTag);
            BeamableLogger.LogError(e);
        }
    }
}