using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Server;
using Beamable.StellarFederation.Features.Scheduler;

namespace Beamable.StellarFederation;

public partial class StellarFederation
{
    [AdminOnlyCallable, SwaggerCategory("Scheduler")]
    public async Task Jobs(bool enable)
    {
        if (enable)
            await Provider.GetService<SchedulerService>().Start();
        await Provider.GetService<SchedulerService>().End();
    }

    [ServerCallable, SwaggerCategory("Scheduler")]
    public async Promise BlockProcessor()
    {
        BeamableLogger.Log("hello from BlockProcessor");
    }
}