using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Commerce;
using Beamable.Common.Content;
using Beamable.Server;
using Beamable.StellarFederation.Features.Commerce;
using StellarFederationCommon.Store;

namespace Beamable.StellarFederation.Endpoints.Commerce;

public class GetListingsEndpoint(RequestContext requestContext, CommerceApi commerceApi) : IEndpoint
{
    public async Task<GetListingsResponse> GetListings(string? optionalStoreId)
    {
        Optional<string> scope = string.IsNullOrWhiteSpace(optionalStoreId) ? new Optional<string>() : optionalStoreId;
        var response = await commerceApi.ObjectGet(requestContext.UserId, scope);
        return response.ToGetStoresResponse();
    }
}